models:
  prostate_mpmri:
    path: "/usr/backups/models/metadata/xgb.standard.100.pkl"
    matches: ["ADC", "DCE", "DWI", "Others", "T2W"]
    heuristics: "prostate_mpmri"
    filters:
      # body_part_examined: "PROSTATE|PELVIS|GENITOURINARY SYSTEM"
      modality: "MR"
