name: dsp
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - ca-certificates=2022.07.19
  - certifi=2022.9.24
  - ld_impl_linux-64=2.38
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - ncurses=6.3
  - openssl=1.1.1q
  - pip=22.2.2
  - python=3.9.7
  - readline=8.1.2
  - sqlite=3.39.3
  - tk=8.6.12
  - tzdata=2022c
  - wheel=0.37.1
  - xz=5.2.6
  - zlib=1.2.12
  - pip:
    - catboost>=1.1
    - dill>=0.3.5.1
    - numpy>=1.23.4
    - pandas>=1.5.0
    - polars>=0.16.1
    - pydicom>=2.3.0
    - scipy>=1.9.2
    - pyarrow==11.0.0
