name: dsp
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - ca-certificates=2022.07.19
  - certifi=2022.9.24
  - ld_impl_linux-64=2.38
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - ncurses=6.3
  - openssl=1.1.1q
  - pip=22.2.2
  - python=3.9.7
  - readline=8.1.2
  - sqlite=3.39.3
  - tk=8.6.12
  - tzdata=2022c
  - wheel=0.37.1
  - xz=5.2.6
  - zlib=1.2.12
  - pip:
    - catboost==1.1
    - charset-normalizer==2.1.1
    - cloudpickle==2.2.0
    - contourpy==1.0.5
    - cycler==0.11.0
    - dill==0.3.5.1
    - docopt==0.6.2
    - fonttools==4.37.4
    - idna==3.4
    - joblib==1.2.0
    - kiwisolver==1.4.4
    - numpy==1.21.6
    - packaging==21.3
    - pandas==1.5.0
    - pipreqs==0.4.11
    - polars==0.16.1
    - psutil==5.9.2
    - pyarrow==11.0.0
    - pydicom==2.3.0
    - pyparsing==3.0.9
    - python-dateutil==2.8.2
    - pytz==2022.4
    - requests==2.28.1
    - setuptools==59.8.0
    - six==1.16.0
    - slicer==0.0.7
    - tenacity==8.1.0
    - threadpoolctl==3.1.0
    - tqdm==4.64.1
    - urllib3==1.26.12
    - yarg==0.1.9
