text_sep_cols = [
    "image_type",
    "sequence_variant",
    "diffusion_bvalue",
    "diffusion_bvalue_ge",
    "diffusion_bvalue_siemens",
    "diffusion_bvalue_final",
    "in_plane_phase_encoding_direction",
    "mr_acquisition_type",
    "patient_position",
    "manufacturer",
    "manufacturer_model_name",
    "receive_coil_name",
    "transmit_coil_name",
    "scanning_sequence",
    "software_versions",
    "scan_options",
    "photometric_interpretation",
    "modality",
    "series_description",
]

num_sep_cols = [
    "acquisition_matrix",
    "echo_time",
    "echo_train_length",
    "repetition_time",
    "flip_angle",
    "reconstruction_matrix",
    "magnetic_field_strength",
    "number_of_phase_encoding_steps",
    "percent_phase_field_of_view",
    "pixel_bandwidth",
    "sar",
    "slice_thickness",
    "temporal_resolution",
    "image_orientation_patient",
    "inversion_time",
    "pixel_spacing",
    "number_of_echos",
    "number_of_temporal_positions",
]

num_cols = [
    "number_of_images",
    "image_mean",
    "image_std",
    "image_min",
    "image_max",
    "image_median",
    "image_skew",
    "image_kurtosis",
    "image_entropy",
    "image_rms",
    "image_blur_effect",
    "image_moment_0",
    "image_moment_1",
    "image_moment_2",
    "image_moment_3",
    "image_moment_4",
    "image_moment_5",
    "image_moment_6",
    "image_intertia_tensor_eigval_0",
    "image_intertia_tensor_eigval_1",
]

cols_to_drop = [
    "study_uid",
    "series_uid",
    "class",
    "diffusion_directionality",
    "spectrally_selected_suppression",
    "reconstruction_matrix",
    "number_of_phase_encoding_steps",
    "inversion_time",
    "image_x",
    "image_y",
    "seg",
    "valid",
]

replace_cols = {
    "diffusion_bvalue": "-",
    "diffusion_bvalue_ge": "-",
    "diffusion_bvalue_siemens": "-",
    "diffusion_bvalue_final": "-",
    "number_of_echos": "1",
    "number_of_temporal_positions": "1",
    "temporal_resolution": "0",
}
